spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: file-service
          uri: lb://file-service
          predicates:
            - Path=/api/files/**
        - id: code-service
          uri: lb://code-service
          predicates:
            - Path=/api/codes/**
        - id: item-service
          uri: lb://item-service
          predicates:
            - Path=/api/items/**
        - id: discovery-server
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/web
          filters:
            - SetPath=/
        - id: discovery-server-static
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/**
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: http://localhost:8181/realms/spring-boot-microservices-realm
eureka:
  client:
    service-url: { "defaultZone": http://localhost:8761/eureka }
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
  level:
    root: info
    org.springframework.cloud.gateway.route.RouteDefinition: info
    org:
      springframework:
        cloud:
          gateway: trace
management:
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0